<a href="https://colab.research.google.com/github/fatimaa909/tip-calculator/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Admission_Predict.csv')

In [3]:
data.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [4]:
data.tail()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [5]:
data.shape

(400, 9)

In [6]:
data.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [7]:
data.info

<bound method DataFrame.info of      Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65
1             2        324          107                  4  4.0   4.5  8.87
2             3        316          104                  3  3.0   3.5  8.00
3             4        322          110                  3  3.5   2.5  8.67
4             5        314          103                  2  2.0   3.0  8.21
..          ...        ...          ...                ...  ...   ...   ...
395         396        324          110                  3  3.5   3.5  9.04
396         397        325          107                  3  3.0   3.5  9.11
397         398        330          116                  4  5.0   4.5  9.45
398         399        312          103                  3  3.5   4.0  8.78
399         400        333          117                  4  5.0   4.0  9.66

     Research  Chance of Admit
0           1              0.92
1           1              0.76
2           1              0.72
3           1              0.80
4           0              0.65
..        ...               ...
395         1              0.82
396         1              0.84
397         1              0.91
398         0              0.67
399         1              0.95

[400 rows x 9 columns]>

In [8]:
data['University Rating'].dtype

dtype('int64')

In [9]:
data['University Rating'].unique

<bound method Series.unique of 0      4
1      4
2      3
3      3
4      2
      ..
395    3
396    3
397    4
398    3
399    4
Name: University Rating, Length: 400, dtype: int64>

In [10]:
data['University Rating'].nunique

<bound method IndexOpsMixin.nunique of 0      4
1      4
2      3
3      3
4      2
      ..
395    3
396    3
397    4
398    3
399    4
Name: University Rating, Length: 400, dtype: int64>

In [11]:
data['University Rating'].value_counts

<bound method IndexOpsMixin.value_counts of 0      4
1      4
2      3
3      3
4      2
      ..
395    3
396    3
397    4
398    3
399    4
Name: University Rating, Length: 400, dtype: int64>

In [12]:
data[data['University Rating']==2]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
4,5,314,103,2,2.0,3.0,8.21,0,0.65
7,8,308,101,2,3.0,4.0,7.90,0,0.68
27,28,298,98,2,1.5,2.5,7.50,1,0.44
29,30,310,99,2,1.5,2.0,7.30,0,0.54
30,31,300,97,2,3.0,3.0,8.10,1,0.65
...,...,...,...,...,...,...,...,...,...
386,387,302,101,2,2.5,3.5,7.96,0,0.46
387,388,307,105,2,2.0,3.5,8.10,0,0.53
388,389,296,97,2,1.5,2.0,7.80,0,0.49
390,391,314,102,2,2.0,2.5,8.24,0,0.64
393,394,317,104,2,3.0,3.0,8.76,0,0.77

In [13]:
data[data['University Rating']!=2]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
5,6,330,115,5,4.5,3.0,9.34,1,0.90
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [18]:
data = data.drop(columns = 'Chance of Admit ', axis = 0)

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [19]:
data.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
0,1,337,118,4,4.5,4.5,9.65,1
1,2,324,107,4,4.0,4.5,8.87,1
2,3,316,104,3,3.0,3.5,8.00,1
3,4,322,110,3,3.5,2.5,8.67,1
4,5,314,103,2,2.0,3.0,8.21,0

In [20]:
data.CGPA.value_counts()

8.00    9
8.76    8
8.56    7
9.11    6
8.64    6
       ..
9.32    1
9.48    1
9.56    1
7.28    1
7.96    1
Name: CGPA, Length: 168, dtype: int64

In [27]:
#iloc function takes as a parameter the rows and coloumn indices and gives you the subset of the DataFRame accordingly. here i am taking the first 10 rowns of data and index 5th to index 10th columns

In [22]:
data.iloc[:200,3:]

     University Rating  SOP  LOR   CGPA  Research
0                    4  4.5   4.5  9.65         1
1                    4  4.0   4.5  8.87         1
2                    3  3.0   3.5  8.00         1
3                    3  3.5   2.5  8.67         1
4                    2  2.0   3.0  8.21         0
..                 ...  ...   ...   ...       ...
195                  2  3.0   3.5  8.52         1
196                  2  3.0   2.5  8.26         0
197                  2  3.5   2.5  8.33         0
198                  3  4.5   4.5  8.43         0
199                  3  4.0   4.5  8.69         0

[200 rows x 5 columns]

In [28]:
#loc function does almost the similar operation as .iloc() function.But jere we can specify exactly which row and index we want and also the name of the columns we want in our subset

In [30]:
data.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research'],
      dtype='object')

In [32]:
data.loc[[3,10,14,23],['GRE Score', 'TOEFL Score', 'University Rating']]

    GRE Score  TOEFL Score  University Rating
3         322          110                  3
10        325          106                  3
14        311          104                  3
23        334          119                  5

In [34]:
#taking the random sample of data
data.sample(n=200)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
268,269,327,113,4,4.5,5.0,9.14,0
89,90,316,109,4,4.5,3.5,8.76,1
70,71,332,118,5,5.0,5.0,9.64,1
272,273,294,95,1,1.5,1.5,7.64,0
319,320,327,113,4,3.5,3.0,8.69,1
...,...,...,...,...,...,...,...,...
38,39,304,105,1,3.0,1.5,7.50,0
100,101,322,107,3,3.5,3.5,8.46,1
325,326,326,116,3,3.5,4.0,9.14,1
14,15,311,104,3,3.5,2.0,8.20,1
383,384,300,100,3,3.0,3.5,8.26,0

In [43]:
#create an ARRAY
array = ['A','B','C','D','E','F']
array

['A', 'B', 'C', 'D', 'E', 'F']

In [44]:
#CREATE A SERIES
series_obj = pd.Series(array)
series_obj

0    A
1    B
2    C
3    D
4    E
5    F
dtype: object

In [45]:
#CONVERT SERIES OBJECT INTO ARRAY
arr = series_obj.values
arr.shape

(6,)

In [46]:
#RESHAPING SERIES
reshaped_arr = arr.reshape((2,3))

In [47]:
reshaped_arr

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype=object)

In [48]:
#NULL VALUES
#IN PANDAS MISSING DATA IS REPRESENTED BY TWO VALUES:
#NONE: IT IS A PYTHON SINGLETON OBJECT THAT IS OFTEN USED FOR MISSING DATA IN PYTHON CODE.
#NAN : IS A SPECIAL FLOATING - POINT VALUE RECOGNISED BY ALL SYSTEM THAT USE THE STANDARD IEEE FLOATING - POINT REPRESENTATIO

In [49]:
import numpy as np
import pandas as pd

In [55]:
#dictionary of Lists
dict = {'First Score':[100,90,np.nan,95],
     'Second Score':[30,45,32,np.nan],
     'Third Score':[np.nan,40,89,23]}

#CREATE A DATAFRAME FROM LIST
df = pd.DataFrame(dict)
df.isnull()

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [ ]:
#filling the missing values

In [56]:
df.fillna(87)

   First Score  Second Score  Third Score
0        100.0          30.0         87.0
1         90.0          45.0         40.0
2         87.0          32.0         89.0
3         95.0          87.0         23.0

In [57]:
#will replace the NaN value in dataframe with the value - 99
df.replace(to_replace = np.nan, value = -99)

   First Score  Second Score  Third Score
0        100.0          30.0        -99.0
1         90.0          45.0         40.0
2        -99.0          32.0         89.0
3         95.0         -99.0         23.0

In [62]:
#using dropna() function
df.dropna()

   First Score  Second Score  Third Score
1         90.0          45.0         40.0

<bound method NDFrame.head of    First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          32.0         89.0
3         95.0           NaN         23.0>